import { ThemeProvider } from "@/components/themeProvider";
import "./globals.css";
import { Inter } from "next/font/google";
import { Navigation } from "@/components/navigation-menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app"
};

export default function RootLayout({
   children
}: {
   children: React.ReactNode;
}) {
   return (
      <html lang="en">
         <body className={inter.className}>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
               <Navigation />
               <main className="mt-16 container">{children}</main>
            </ThemeProvider>
         </body>
      </html>
   );
}
